import { Resend } from 'resend';
import { config } from '../config.js';
import type { DailyBriefingReport, ChatbotIssue } from '../types/index.js';

const resend = new Resend(config.RESEND_API_KEY);

function generateHtml(report: DailyBriefingReport): string {
    const issuesHtml = report.issues.map((issue: ChatbotIssue) => `
        <div style="margin-bottom: 20px; padding: 15px; border-left: 4px solid ${getSeverityColor(issue.severity)}; background-color: #f9f9f9;">
            <h3 style="margin: 0 0 10px 0; color: #333;">${issue.severity} Severity: ${issue.summary}</h3>
            <p style="margin: 0 0 5px 0;"><strong>Author:</strong> ${issue.author}</p>
            <p style="margin: 0 0 10px 0; color: #666; font-size: 14px;">"...${issue.rawText.substring(0, 300)}..."</p>
            <a href="${issue.postUrl}" style="color: #0077b5; text-decoration: none; font-weight: bold;">Read Full Post on LinkedIn →</a>
        </div>
    `).join('');

    return `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
            <h1 style="color: #0077b5;">Daily AI Chatbot Post Briefing</h1>
            <p><strong>Date:</strong> ${report.date}</p>
            <p><strong>Posts Scanned:</strong> ${report.totalPostsScanned}</p>
            <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
            
            ${report.issues.length > 0 ? issuesHtml : '<p>No specific reports of AI chatbot misbehavior were identified in today\'s post scan.</p>'}
            
            <footer style="margin-top: 40px; font-size: 12px; color: #999; text-align: center;">
                <p>This briefing was automatically generated by Antigravity AI.</p>
            </footer>
        </div>
    `;
}

function getSeverityColor(severity: ChatbotIssue['severity']): string {
    switch (severity) {
        case 'Critical': return '#d93025';
        case 'High': return '#f29900';
        case 'Medium': return '#1a73e8';
        case 'Low': return '#5f6368';
        default: return '#5f6368';
    }
}

export async function sendBriefing(report: DailyBriefingReport): Promise<void> {
    console.log(`✉️ Sending briefing email to ${config.RECIPIENT_EMAIL}...`);

    try {
        const { data, error } = await resend.emails.send({
            from: config.FROM_EMAIL,
            to: [config.RECIPIENT_EMAIL],
            subject: `Daily Briefing: AI Chatbot Issues (Posts) - ${report.date}`,
            html: generateHtml(report),
        });

        if (error) {
            console.error("❌ Resend email failed:", error);
        } else {
            console.log("✅ Briefing email sent successfully!", data?.id);
        }
    } catch (error) {
        console.error("❌ Resend service error:", error);
    }
}
