import { Resend } from 'resend';
import { config } from '../config.js';
const resend = new Resend(config.RESEND_API_KEY);
function generateHtml(report) {
    const issuesHtml = report.issues.map((issue) => `
        <div style="margin-bottom: 20px; padding: 15px; border-left: 4px solid ${getSeverityColor(issue.severity)}; background-color: #f9f9f9;">
            <h3 style="margin: 0 0 10px 0; color: #333;">${issue.severity} Severity: ${issue.summary}</h3>
            <p style="margin: 0 0 5px 0;"><strong>Commenter:</strong> ${issue.commenter}</p>
            <p style="margin: 0 0 10px 0; font-style: italic; color: #666;">"${issue.rawText}"</p>
            <a href="${issue.postUrl}" style="color: #0077b5; text-decoration: none;">View Original LinkedIn Post →</a>
        </div>
    `).join('');
    return `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
            <h1 style="color: #0077b5;">Daily AI Chatbot Briefing</h1>
            <p><strong>Date:</strong> ${report.date}</p>
            <p><strong>Comments Scanned:</strong> ${report.totalCommentsScanned}</p>
            <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
            
            ${report.issues.length > 0 ? issuesHtml : '<p>No chatbot misbehavior issues were identified in today\'s scan.</p>'}
            
            <footer style="margin-top: 40px; font-size: 12px; color: #999; text-align: center;">
                <p>This briefing was automatically generated by Antigravity AI.</p>
            </footer>
        </div>
    `;
}
function getSeverityColor(severity) {
    switch (severity) {
        case 'Critical': return '#d93025';
        case 'High': return '#f29900';
        case 'Medium': return '#1a73e8';
        case 'Low': return '#5f6368';
        default: return '#5f6368';
    }
}
export async function sendBriefing(report) {
    console.log(`✉️ Sending briefing email to ${config.RECIPIENT_EMAIL}...`);
    try {
        const { data, error } = await resend.emails.send({
            from: config.FROM_EMAIL,
            to: [config.RECIPIENT_EMAIL],
            subject: `Daily Briefing: AI Chatbot Issues - ${report.date}`,
            html: generateHtml(report),
        });
        if (error) {
            console.error("❌ Resend email failed:", error);
        }
        else {
            console.log("✅ Briefing email sent successfully!", data?.id);
        }
    }
    catch (error) {
        console.error("❌ Resend service error:", error);
    }
}
//# sourceMappingURL=resend.js.map